CREATE TABLE IF NOT EXISTS `#__miwosql_queries` (
`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT ,
`title` VARCHAR(255) NOT NULL DEFAULT '',
`query` TEXT NOT NULL DEFAULT '',
PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
